export const ASSIGN_JWT_TOKEN = 'ASSIGN_JWT_TOKEN';
export const ASSIGN_BABIES = 'ASSIGN_BABIES';
export const ASSIGN_FOOD_ENTRIES = 'ASSIGN_FOOD_ENTRIES';
export const ASSIGN_CURRENT_FOOD_ENTRY = 'ASSIGN_CURRENT_FOOD_ENTRY';
export const ASSIGN_USER_DATA = 'ASSIGN_USER_DATA';
